export const UPDATE_WATCHLIST = 'UPDATE_WATCHLIST'
export const GET_PROFILE_INFO = 'GET_PROFILE_INFO'
export const UPLOAD_POST = 'UPLOAD_POST'
export const MY_POSTS = 'MY_POSTS'
export const GET_FOLLOWERS = 'GET_FOLLOWERS'
export const GET_FOLLOWING = 'GET_FOLLOWING'
export const GET_FOLLOWERS_MINE = 'GET_FOLLOWERS_MINE'
export const GET_FOLLOWING_MINE = 'GET_FOLLOWING_MINE'
export const WATCHLIST_LOADING = 'WATCHLIST_LOADING'
export const NOTIFICATION_DATA = "NOTIFICATION_DATA"

