export const GET_USER = 'GET_USER';
export const GET_USER_WATCHLIST = "GET_USER_WATCHLIST";
export const GET_OTHER_USER_FOLLOWINGS =
  'GET_OTHER_USER_FOLLOWINGS';
export const GET_OTHER_USER_FOLLOWERS = 'GET_OTHER_USER_FOLLOWERS';
export const CLEAR_OTHER_USER_FOLLOWINGS_FOLLOWERS =
  'CLEAR_OTHER_USER_FOLLOWINGS_FOLLOWERS';
export const GET_OTHER_USER_POSTS = 'GET_OTHER_USER_POSTS';
export const LOAD_MORE_OTHER_POSTS = 'LOAD_MORE_OTHER_POSTS';
export const GET_USER_FOLLOWINGS = 'GET_USER_FOLLOWINGS';
export const GET_USER_FOLLOWERS = 'GET_USER_FOLLOWERS';